### ISSUE TITLE
After 0.2.16 Update I get always NoneType error on one account

### ISSUE THREAD

**Issue by SteffenM-DE** [cyberjunky/home-assistant-garmin_connect#82]
We have two Garmin accounts and one showing this error after update to 0.2.16:

Setup erneut versuchen: 'NoneType' object has no attribute 'json'

Delete and new creating the account shows this error too. HA Log shows many details like this :

`2023-05-24 10:05:50.840 ERROR (MainThread) [custom_components.garmin_connect] Unexpected error fetching garmin_connect data: 'NoneType' object has no attribute 'json'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 258, in _async_refresh
    self.data = await self._async_update_data()
  File "/config/custom_components/garmin_connect/__init__.py", line 129, in _async_update_data
    gear_stats = await asyncio.gather(*tasks)
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.10/site-packages/garminconnect/__init__.py", line 856, in get_gear_stats
    return self.modern_rest_client.get(url).json()
AttributeError: 'NoneType' object has no attribute 'json'
`

**Comment by rainepretorius** [comment]
I also get this error: 
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 283, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/garmin_connect/__init__.py", line 118, in _async_update_data
    alarms = await self.hass.async_add_executor_job(self._api.get_device_alarms)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/garminconnect/__init__.py", line 695, in get_device_alarms
    device_settings = self.get_device_settings(device["deviceId"])
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/garminconnect/__init__.py", line 685, in get_device_settings
    return self.modern_rest_client.get(url).json()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'json'

**Comment by horbye** [comment]
Been getting this error lately aswell, on 2 different Garmin watches:
`2023-07-01 12:53:25.041 DEBUG (MainThread) [custom_components.garmin_connect] {'userProfileId': 1234567, 'totalKilocalories': 612.0, 'activeKilocalories': 1.0, 'bmrKilocalories': 611.0, 'wellnessKilocalories': 612.0, 'burnedKilocalories': None, 'consumedKilocalories': None, 'remainingKilocalories': 612.0, 'totalSteps': 59, 'netCalorieGoal': 2560, 'totalDistanceMeters': 51, 'wellnessDistanceMeters': 51, 'wellnessActiveKilocalories': 1.0, 'netRemainingKilocalories': 2561.0, 'userDailySummaryId': 2316446, 'calendarDate': '2023-07-01', 'rule': {'typeId': 3, 'typeKey': 'subscribers'}, 'uuid': 'b5dd2984c51c40e59b65fb8ba01bb679', 'dailyStepGoal': 10000, 'wellnessStartTimeGmt': '2023-06-30T22:00:00.0', 'wellnessStartTimeLocal': '2023-07-01T00:00:00.0', 'wellnessEndTimeGmt': '2023-07-01T04:24:00.0', 'wellnessEndTimeLocal': '2023-07-01T06:24:00.0', 'durationInMilliseconds': 23040000, 'wellnessDescription': None, 'highlyActiveSeconds': 60, 'activeSeconds': 120, 'sedentarySeconds': 22860, 'sleepingSeconds': 0, 'includesWellnessData': True, 'includesActivityData': False, 'includesCalorieConsumedData': False, 'privacyProtected': False, 'moderateIntensityMinutes': 0, 'vigorousIntensityMinutes': 0, 'floorsAscendedInMeters': 0.0, 'floorsDescendedInMeters': 0.0, 'floorsAscended': 0.0, 'floorsDescended': 0.0, 'intensityMinutesGoal': 150, 'userFloorsAscendedGoal': 10, 'minHeartRate': 61, 'maxHeartRate': 64, 'restingHeartRate': None, 'lastSevenDaysAvgRestingHeartRate': None, 'source': 'GARMIN', 'averageStressLevel': 17, 'maxStressLevel': 24, 'stressDuration': None, 'restStressDuration': 1440, 'activityStressDuration': None, 'uncategorizedStressDuration': 21600, 'totalStressDuration': 23040, 'lowStressDuration': None, 'mediumStressDuration': None, 'highStressDuration': None, 'stressPercentage': 0.0, 'restStressPercentage': 6.25, 'activityStressPercentage': 0.0, 'uncategorizedStressPercentage': 93.75, 'lowStressPercentage': 0.0, 'mediumStressPercentage': 0.0, 'highStressPercentage': 0.0, 'stressQualifier': 'UNKNOWN', 'measurableAwakeDuration': 1440, 'measurableAsleepDuration': 0, 'lastSyncTimestampGMT': '2023-07-01T04:24:36.586', 'minAvgHeartRate': 61, 'maxAvgHeartRate': 64, 'bodyBatteryChargedValue': 0, 'bodyBatteryDrainedValue': 0, 'bodyBatteryHighestValue': 99, 'bodyBatteryLowestValue': 99, 'bodyBatteryMostRecentValue': 99, 'bodyBatteryVersion': 2.0, 'abnormalHeartRateAlertsCount': None, 'averageSpo2': None, 'lowestSpo2': None, 'latestSpo2': None, 'latestSpo2ReadingTimeGmt': None, 'latestSpo2ReadingTimeLocal': None, 'averageMonitoringEnvironmentAltitude': 15.0, 'restingCaloriesFromActivity': None, 'avgWakingRespirationValue': 14.0, 'highestRespirationValue': 16.0, 'lowestRespirationValue': 12.0, 'latestRespirationValue': 14.0, 'latestRespirationTimeGMT': '2023-07-01T04:24:00.0'}
2023-07-01 12:53:25.416 DEBUG (MainThread) [custom_components.garmin_connect] {'startDate': '2023-07-01', 'endDate': '2023-07-01', 'dateWeightList': [], 'totalAverage': {'from': 1688169600000, 'until': 1688255999999, 'weight': None, 'bmi': None, 'bodyFat': None, 'bodyWater': None, 'boneMass': None, 'muscleMass': None, 'physiqueRating': None, 'visceralFat': None, 'metabolicAge': None}}
2023-07-01 12:53:26.381 DEBUG (MainThread) [custom_components.garmin_connect] [{'alarmMode': 'ON', 'alarmTime': 360, 'alarmDays': ['M', 'Tu', 'W', 'Th', 'F'], 'alarmSound': 'VIBRATION', 'alarmId': 163607284, 'changeState': 'UNCHANGED', 'backlight': 'ON', 'enabled': None, 'alarmMessage': None, 'alarmImageId': None, 'alarmIcon': None, 'alarmType': None}, {'alarmMode': 'OFF', 'alarmTime': 330, 'alarmDays': ['M', 'Tu', 'W', 'Th', 'F'], 'alarmSound': 'VIBRATION', 'alarmId': 167533132, 'changeState': 'UNCHANGED', 'backlight': 'ON', 'enabled': None, 'alarmMessage': None, 'alarmImageId': None, 'alarmIcon': None, 'alarmType': None}, {'alarmMode': 'OFF', 'alarmTime': 420, 'alarmDays': ['M', 'Tu', 'W', 'Th', 'F'], 'alarmSound': 'VIBRATION', 'alarmId': 1675721755, 'changeState': 'UNCHANGED', 'backlight': 'ON', 'enabled': None, 'alarmMessage': None, 'alarmImageId': None, 'alarmIcon': None, 'alarmType': None}, {'alarmMode': 'OFF', 'alarmTime': 180, 'alarmDays': ['ONCE'], 'alarmSound': 'VIBRATION', 'alarmId': 168693929, 'changeState': 'UNCHANGED', 'backlight': 'ON', 'enabled': None, 'alarmMessage': None, 'alarmImageId': None, 'alarmIcon': None, 'alarmType': None}]
2023-07-01 12:53:26.774 ERROR (MainThread) [custom_components.garmin_connect] Unexpected error fetching garmin_connect data: 'NoneType' object has no attribute 'json'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 283, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/garmin_connect/__init__.py", line 129, in _async_update_data
    gear_stats = await asyncio.gather(*tasks)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/garminconnect/__init__.py", line 856, in get_gear_stats
    return self.modern_rest_client.get(url).json()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'json'
2023-07-01 12:53:26.781 DEBUG (MainThread) [custom_components.garmin_connect] Finished fetching garmin_connect data in 1.967 seconds (success: False)

**Comment by horbye** [comment]
Figured what was wrong for me.
a few years ago, I added a bike in the phone app, this was not visible in Garmin Connect, after removing the bike in the phone app, gear was able to sync without errors

**Comment by cyberjunky** [comment]
Closing because old ticket and newer framework in place.
