### ISSUE TITLE
Sensor Next alarm

### ISSUE THREAD

**Issue by neopsyko** [cyberjunky/home-assistant-garmin_connect#446]
Hello,

Sensor Next alarm is not working in the last version 3.0 (beta 6) :

[custom_components.garmin_connect.coordinator] Finished fetching garmin_connect_training data in 1.547 seconds (success: True)
2026-04-09 20:31:52.867 ERROR (MainThread) [homeassistant.components.sensor] Error adding entity sensor.garmin_connect_next_alarm for domain sensor with platform garmin_connect
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 621, in state
    if value.tzinfo is None:
       ^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'tzinfo'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 680, in _async_add_entities
    await self._async_add_entity(
        entity, False, entity_registry, config_subentry_id
    )
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 998, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1431, in add_to_platform_finish
    self.async_write_ha_state()
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1050, in async_write_ha_state
    self._async_write_ha_state()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1199, in _async_write_ha_state
    ) = self.__async_calculate_state()
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1106, in __async_calculate_state
    state = self._stringify_state(available)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1056, in _stringify_state
    if (state := self.state) is None:
                 ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 632, in state
    raise ValueError(
    ...<2 lines>...
    ) from err
ValueError: Invalid datetime: sensor.garmin_connect_next_alarm has timestamp device class but provides state 2026-04-10T12:00:00+02:00:<class 'str'> resulting in ''str' object has no attribute 'tzinfo'

Thx.

**Comment by timvp94** [comment]
in beta 8 this error is still present

**Comment by cyberjunky** [comment]
> in beta 8 this error is still present

You refer to next alarm error right? I had no time to test it, I will fix it tomorrow.

**Comment by timvp94** [comment]
Yes indeed! no problem, rest of the integration is working great again!

**Comment by cyberjunky** [comment]
Fixed in beta-09

**Comment by saikimecky** [comment]
I tested beta-09. still doesnt work. Sensor stays "unknown".  any hints?

**Comment by cyberjunky** [comment]
> I tested beta-09. still doesnt work. Sensor stays "unknown". any hints?

You do have it synced right, do you have multiple alarms set?
I have one and it works

<img width="564" height="88" alt="Image" src="https://github.com/user-attachments/assets/95d7d01d-a802-4408-ab55-217148b2d868" />

**Comment by saikimecky** [comment]
i have multiple alarms, but only 1 is active at the moment. synced with garmin app und waited 30+ mins. but sensor stays unknown.

**Comment by cyberjunky** [comment]
> i have multiple alarms, but only 1 is active at the moment. synced with garmin app und waited 30+ mins. but sensor stays unknown.

OK i will test that scenario

**Comment by cyberjunky** [comment]
It was not parsing recurring alarms correctly, should be fixed in beta-10

**Comment by timvp94** [comment]
Works great again, thank so much!
