### ISSUE TITLE
Entities showing unknown values

### ISSUE THREAD

**Issue by motionist** [cyberjunky/home-assistant-garmin_connect#94]
Since update to core 2023.7.3 I've been unable to read entity called for entity Next Alarm Time (used as trigger in automations 

Wire a few other entities are displaying unknown as well.

**Comment by otorikateo** [comment]
Hello, same here, all sensors display 'unknown' unfortunatelly

**Comment by GalchenkoAlexander** [comment]
The integration does not work with core 2023.8.1 version.  All entities are unavailable.

Logger: homeassistant.config_entries
Source: custom_components/garmin_connect/__init__.py:40
Integration: Garmin Connect ([documentation](https://github.com/cyberjunky/home-assistant-garmin_connect), [issues](https://github.com/cyberjunky/home-assistant-garmin_connect/issues))
First occurred: 11:31:38 (1 occurrences)
Last logged: 11:31:38

Error setting up entry <my-email> for garmin_connect
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 388, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/garmin_connect/__init__.py", line 40, in async_setup_entry
    hass.config_entries.async_setup_platforms(entry, PLATFORMS)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'ConfigEntries' object has no attribute 'async_setup_platforms'

**Comment by motionist** [comment]
I've noticed for individual alarms, the sensor does work, however when next alarm is a recurring alarm it does not.

**Comment by MarioBerger** [comment]
Here too,
I can only see the riding distance from my bikes.
All other data from my Fenix watch are "unknown"

**Comment by cyberjunky** [comment]
@motionist @MarioBerger can you retry with latest integration- and HA version? (if you still want to use it)

**Comment by kruemelro** [comment]
I have the same problem, (HA 2024.1 and last version of Garmin Addon)
For me it seems that the values go to unknown on midnight:
![image](https://github.com/cyberjunky/home-assistant-garmin_connect/assets/6331424/903f7f37-8a71-48c3-8b65-01591d315fd4)

**Comment by Xanimun** [comment]
I'm having the same issues as @kruemelro . All sensors seem to reset at midnight when they reset to 0. In place of showing the 0 Value, they go to Unavailable until they change to something else (I've tested with steps). I then walk for a bit, open the Garmin Connect app and sync with my smartwatch and then, bam, i can see new values again in HA. Same with everything else.

**Comment by ddt4ever** [comment]
Hi folks!
I actually had the same issue in HA starting from version 2023* i think, in old versions of HA this integration was working fine with my garmin vivosmart HR+.
And the issue was on both HA instances in different countries... So, it looked like the issue is not in this HA integration...
The solution that solved my issue was - reinstall garmin connect on my phone, and delete the garmin vivosmart hr+ in the app of the phone. After a new "pair" of the device in the phone's app i've got everything working again as in the past in my last version of HA :))

**Comment by kruemelro** [comment]
I don't think thats the problem cause i have this issue with the garmin index scale, which doesn't sync over the app at all, it syncs directly to garmin connect over a wifi connection. Also i have this issue with 2 seperate Garmin accounts.
@cyberjunky could i help you in any way to solve this issue? Providing logs and such things,

**Comment by kruemelro** [comment]
I've found the problem and created a pull request #157 with a workaround for the body data. Stress and Sleep Data still getting unknown.

The problem is the api greps these data only for today, and returns unknown if there are no data for today. Thats the reason why the sensors are getting to unknown state on midnight. 

I think a real fix this would to check the values and don't return them if there is so data. But i don't know how to implement this
